name: Lock Threads

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  lock-threads:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lock threads
        uses: dessant/lock-threads@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
