name: Workflow Name
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run action
        uses: dessant/lock-threads@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
