name: Workflow Name
on: [push, pull_request]

jobs:
  job_name:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Lock Threads
      uses: dessant/lock-threads@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
