name: Lock Threads

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v4
        with:
          github-token: ${{ secrets.VALID_TOKEN }}
          issue-lock-inactive-days: '30'
          pr-lock-inactive-days: '30'
